# -*- coding: utf-8 -*-
"""penguins.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLKfRhi0ZMWY5-Jo_qWo6ryCRPUYOHVp
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile penguins_app.py
# import streamlit as st
# import matplotlib.pyplot as plt
# import pandas as pd
# import plotly.express as px
# import seaborn as sns
# import random
# 
# st.title('Viana Rocks 🐧🐧🐧🐧🐧')
# 
# #Bring in the data
# df=sns.load_dataset('penguins')
# df=df.dropna()
# 
# #Show the data
# st.dataframe(df)
# 
# #Show the barplot
# fig=px.bar(tips_by_day,x='day',y='total_bill',title='Average Bill by Day')
# st.plotly_chart(fig)
# 
# #Show the boxplot
# fig=px.box(df,x='island',y='body_mass_g',title='Body Mass by Island')
# st.plotly_chart(fig)
# 
# #Show the scatterplot
# fig_scatter=px.scatter(df,x='body_mass_g',y='bill_length_mm',color='species',title='Body Mass vs Bill Length')
# st.plotly_chart(fig_scatter)
# 
# #violin plot
# fig=px.violin(penguins,x="species",y="body_mass_g",color="sex",box=True,points="all")
# fig.update_layout(title="Body Mass by Species and Sex")
# st.plotly_chart(fig)
#