# -*- coding: utf-8 -*-
"""VPen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19s0eYS9rY-KeIGiRllPmHGM5uno5Rr--
"""

import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import seaborn as sns
import random
import statsmodels.api as sm

"""Intro to plotly getting data from seaborn"""

tips=sns.load_dataset('tips')
tips.head()

#average by day - intro to groupby
tips_by_day=tips.groupby('day')['total_bill'].agg('mean').reset_index()
tips_by_day

fig=px.bar(tips_by_day,x='day',y='total_bill',title='Average Bill by Day')
fig.show()

fig=px.scatter(tips,x='tip',y='total_bill',title='Average Bill by Day',trendline='ols',color='size')
fig.show()

df=sns.load_dataset('penguins')
df.dropna()

"""Bar chart by island"""

penguin_counts=df['island'].value_counts().reset_index()
fig=px.bar(penguin_counts,x='island',y='count',color='island',title='Count by Island')
fig.show()

fig=px.box(df,x='island',y='body_mass_g',title='Body Mass by Island')
fig.show()

"""Scatterplot for bodymass and bill length"""

fig_scatter=px.scatter(df,x='body_mass_g',y='bill_length_mm',color='species',title='Body Mass vs Bill Length')
fig_scatter.show()

"""Making maps in Plotly"""

import random
island_coords={"Biscoe":(-63.8,-63.4), "Dream":(-64.7, -62.9), "Torgersen":(-64.8,-64.1)}
df["latitude"]=df["island"].map(lambda x:island_coords[x][0]+ random.uniform(-0.1, 0.1))
df["longitude"]=df["island"].map(lambda x:island_coords[x][1]+ random.uniform(-0.1, 0.1))

fig_map=px.scatter_map(df,lat="latitude", lon="longitude",color="species", color_discrete_map={"Adelie": "blue",
                                     "Chinstrap": "red",
                                     "Gentoo": "green"}, title="This is a plot of penguins based on the color of their poop", zoom=5, map_style="open-street-map")
fig_map.show()

"""# Making a streamlit app from my plotly work"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile penguins_app.py
# import streamlit as st
# import matplotlib.pyplot as plt
# import pandas as pd
# import plotly.express as px
# import seaborn as sns
# import random
# import statsmodels.api as sm
# 
# st.title('Viana Rocks 🐧🐧🐧🐧🐧')
# 
# #Bring in the data
# df=sns.load_dataset('penguins')
# df=df.dropna()
# 
# #Show the data
# st.dataframe(df)
# 
# #Show the barplot
# fig=px.bar(tips_by_day,x='day',y='total_bill',title='Average Bill by Day')
# st.plotly_chart(fig)
# 
# #Show the boxplot
# fig=px.box(df,x='island',y='body_mass_g',title='Body Mass by Island')
# st.plotly_chart(fig)
# 
# #Show the scatterplot
# fig_scatter=px.scatter(df,x='body_mass_g',y='bill_length_mm',color='species',title='Body Mass vs Bill Length')
# st.plotly_chart(fig_scatter)
# 
# #violin plot
# fig=px.violin(penguins,x="species",y="body_mass_g",color="sex",box=True,points="all")
# fig.update_layout(title="Body Mass by Species and Sex")
# st.plotly_chart(fig)
#